add `workflow_configuration_objects` slot
microbiomedata/berkeley-schema-fy24 pull request #136
Opened 2024-04-22 19:10 UTC by brynnz22

2024-04-23 15:22 UTC, kheal requested changes

2024-04-23 15:22 UTC, kheal commented on src/data/valid/MetabolomicsAnalysis-1.yaml
I suggest changing slot name to `configuration_data_objects`, so if we want to reuse with other configurations it's more general.  Since the slot sits a `WorkflowExecution` class, I do not think we need to repeat the `workflow` part of the description.

2024-04-24 22:00 UTC, kheal commented
@brynnz22 Following today's discussion at the metadata meeting, I think we can keep the model as is (no new slot) and include the parameter data files as `DataObject` in the `has_output` slots.  If we expanded the `DataCategoryEnum` on the `data_category` slot on `DataObject` class to include `workflow_parameters` that would really simplify things on the schema side while still accomplishing what we are trying to capture.

2024-04-24 22:51 UTC, brynnz22 commented
@kheal That makes sense to me. We would also have to add a new enum to the `FileTypeEnum` for the `data_object_type` slot. Maybe something like `workflow configuration toml` or similar.

2024-04-24 23:05 UTC, kheal commented
@brynnz22 Yes, good call.  I would suggest "corems parameters toml"

2024-04-25 16:06 UTC, brynnz22 commented
@kheal I think we would want something a little more general since some of the toml files are like `EnviroMs.toml` and `CoreMs.toml`.

2024-04-25 16:19 UTC, kheal commented
That mapping is great - though I don't understand why it has the word format..... _configuration_file_ makes more sense to me.

There are two Enums we'll have to update.  The `DataCategoryEnum` for the `data_category` (I suggest adding _workflow_configuration_file_ or something similar) and the `FileTypeEnum` on the `data_object_type` which is more detailed (from what I can tell).  Even though some are EnviroMS and some are MetaMS and some are CoreMS, they are all applied to CoreMS functionality to run the workflows, so I think adding "CoreMS parameter toml" to the `FileTypeEnum` is sufficient.  That value is able to capture the NOM, Metabolomics, and Lipidomics workflow parameters.

2024-04-25 16:28 UTC, closed without merging