Add workflow data object configuration capabilities
microbiomedata/berkeley-schema-fy24 pull request #140
Opened 2024-04-25 16:28 UTC by brynnz22

This PR (related to this initial PR that is closed: https://github.com/microbiomedata/berkeley-schema-fy24/pull/136) adds a`DataCategoryEnum` `permissible_value` of `workflow_parameter` to allow workflow parameter files as `has_input` for `WorfklowExecution`s. It also add a `permissible_value` for the `FileTypeEnum` of `Configuration toml`. Both new permissible values include EDAM mappings.

2024-04-30 16:31 UTC, brynnz22 commented
Unsure about how braod or specific the new permissible file for the `FileTypeEnum` needs to be. Wanted input from @SamuelPurvine

2024-04-30 16:48 UTC, kheal approved these changes
Looks good from my perspective.  Having the configuration tomls for the NOM, metabolomics, and lipidomics workflows is essential for reproducibility.  We can populate these `DataObject` sets programmatically alongside the workflow instances.  The mappings to edam are well matched to our needs, thanks!

2024-04-30 20:50 UTC, turbomam requested changes
I just reread this now and think this will be fine. Thanks for being flexible.

Please 
- modify the description of the new permissible value so that it mentions the things that it will interact with using their exact names from the schema
- add an example data file that shows the pattern by instantiating a Database

2024-04-30 20:52 UTC, turbomam commented
Also please update the PR title to indicate what action was finally taken, adding a new permissible value

2024-05-01 19:05 UTC, kheal commented
@brynnz22  - after talking with @SamuelPurvine, we think `workflow_parameter_data` is better than `workflow_parameter` (the latter sounds like we're capturing a single parameter), and fits better with the other permissible values on that Enum. 

The proteomics workflows will need a different set of permissible values for the `FileTypeEnum` (they are not tomls and there are more than one), so I think being more specific for that value for this specific use case is also valuable (`CoreMS Configuration toml`), but I am open to being overruled on that case. 

Generally speaking though, this approach is valuable and applicable for all the mass-spec 'omics, yay!

2024-05-01 19:38 UTC, brynnz22 commented
@turbomam I included you suggestions - updating the description for the `Configuration Toml` permissible value and including an example data set. 

I also changed the new `DataCateogryEnum` permissible value from `workflow_parameter` to `workflow_parameter_data` and @SamuelPurvine's request to be flexible to proteomics use cases.

2024-05-02 18:11 UTC, turbomam requested changes

2024-05-02 18:11 UTC, turbomam commented on src/schema/basic_slots.yaml
> +          Configuration toml file used by CoreMS in the NomAnlaysis and MetabolomicsAnalysis workflows to
- I don't thin CoreMS is defined anywhere in the schema. At a minimum, please provide a good see also
- please double check that the schema elements that you mention can be looked up verbatim in the docuemtnation or schema files
    - NomAnlaysis -> NomAnalysis

2024-05-02 18:11 UTC, turbomam commented on src/schema/basic_slots.yaml
> +        description: Data generated by a workflow execution planned process
data generation -> DataGeneration 
workflow execution -> WorkflowExecution

2024-05-02 19:15 UTC, turbomam approved these changes
Good conversation with @brynnz22 , ultimately about something that she didn't actually add to the schema.

Will need some followup. see [comments in last commit](https://github.com/microbiomedata/berkeley-schema-fy24/pull/140/commits/81c63a7f7e14c2d61a6abf1b8006a7aef8f5fcd0).

2024-05-02 19:15 UTC, merged