add has_data_generation_parts and examples
microbiomedata/berkeley-schema-fy24 pull request #33
Opened 2023-12-14 22:26 UTC by brynnz22

2023-12-15 17:57 UTC, mslarae13 reviewed
@anastasiyaprymolenna please reference this in your update PR too

2023-12-15 17:57 UTC, mslarae13 commented on src/schema/nmdc.yaml
> +  has_data_generation_parts:
use has_process_parts

has_process_parts will be updated to not have a domain 
has_process_parts slot will be not required, ProtocolExecution will update its slot usage to say has_process_part is required

2023-12-15 18:25 UTC, brynnz22 commented
Added `process_parts` to the `DataGeneration` class. @anastasiyaprymolenna made `has_process_parts` optional, but required for the `ProtocolExecution` class. This is ready for review.

2023-12-15 19:19 UTC, brynnz22 commented
Now changing to use `part_of` for child `DataGeneration` to have `range` `DataGeneration`, and change the current `part_of` slot that has `range` `Study` to be `was_informed_by`.

2023-12-15 20:06 UTC, brynnz22 commented
@brynnz22 change `was_informed_by` to `study_source`

2023-12-18 18:36 UTC, brynnz22 commented
@aclum @cmungall I change the `was_informed_by` to be a new slot called `associated_study`. I made this the name since we have a similar slot called `associated_dois` that function in a similar way. If you approve this, I think we will need to make an issue to update all of the places that currently use `part_of` to link to a study to use `associated_study` instead. The only place I can think of that this will not be applicable to is linking a child study to a parent study, in which case, I believe `part_of` is the right choice. This is ready for review! Thanks.

2023-12-18 18:42 UTC, brynnz22 commented
All in all, since this PR involved a lot of iteration: `part_of` slot in the `DataGeneration` class was changed to from having a value of `Study` to having a `DataGeneration` value to link parts of a data generation (e.g. included sequential sequencing steps) to a parent `DataGeneration` and a new slot was added, called `associated_study` to link `DataGeneration` to its corresponding study. The changes to `process_parts` were in an iteration of this change where we thought we might use `process_parts` to model the sequenctial sequencing, but ultimately decided against it. @anastasiyaprymolenna  made this globally optional, and only required as part of the `slot_usage` for `ProtocolExecution`.

2023-12-18 19:13 UTC, aclum requested changes

2023-12-18 19:13 UTC, aclum commented on src/data/valid/DataGeneration-part_of.yaml
> +id: nmdc:datgen-99-zUCd5N
typecode should be dgns not datgen. I'm surprised this validates @turbomam

2023-12-18 19:13 UTC, aclum commented on src/schema/nmdc.yaml
> +        pattern: "^nmdc:datgen-[0-9][a-z]{0,6}[0-9]-[A-Za-z0-9]{1,}(\\.[A-Za-z0-9]{1,})*(_[A-Za-z0-9_\\.-]+)?$" # better applied as a structured_pattern, but even that might get out of sync from the
I think we should remove this in favor of enforcing the pattern in the Classes and then specifying the range as you have done.

2023-12-18 19:13 UTC, aclum commented on nmdc_schema/nmdc_materialized_patterns.schema.json
> +                    "pattern": "^nmdc:datgen-[0-9][a-z]{0,6}[0-9]-[A-Za-z0-9]{1,}(\\.[A-Za-z0-9]{1,})*(_[A-Za-z0-9_\\.-]+)?$",
can pattern be taken out in favor of enforcing this via range where the value is a class which already has a pattern defined.

2023-12-18 19:13 UTC, aclum commented on nmdc_schema/nmdc_materialized_patterns.schema.json
> +                    "pattern": "^nmdc:sty-[0-9][a-z]{0,6}[0-9]-[A-Za-z0-9]{1,}(\\.[A-Za-z0-9]{1,})*(_[A-Za-z0-9_\\.-]+)?$",
same comment as above wrt not having a pattern, instead enforce via a range

2023-12-18 19:13 UTC, aclum commented on nmdc_schema/nmdc_materialized_patterns.schema.json
> +                    "pattern": "^nmdc:datgen-[0-9][a-z]{0,6}[0-9]-[A-Za-z0-9]{1,}(\\.[A-Za-z0-9]{1,})*(_[A-Za-z0-9_\\.-]+)?$",
We decided not to have a typecode for datgen, instead there are typecodes dgnt and dtms for the subclasses of data generation

2023-12-18 19:23 UTC, brynnz22 commented
Going to redo this PR due to crazy merge conflicts. Will retag everyone.

2023-12-18 19:23 UTC, closed without merging