moved range from slot assertion to slot usage
microbiomedata/berkeley-schema-fy24 pull request #96
Opened 2024-03-08 17:36 UTC by anastasiyaprymolenna

Moved the ` any_of:` range from where we assert `compound` slot to the SolutionComponent class definition as a `slot_usage`. As per @sujaypatil96 suggestion in https://github.com/microbiomedata/nmdc-schema/issues/1666#issuecomment-1915214482 

But it had no change on the `testdoc` generation. The range of `Slot: compound` still comes up as a string instead of the Enum's we require.

2024-03-08 18:40 UTC, turbomam commented
Thansk for trying this

2024-03-08 18:52 UTC, turbomam requested changes
This is very useful experimentation, but I don't want to change the modelling to get better documentation. See additional PR comments.

2024-03-08 18:54 UTC, turbomam commented
@anastasiyaprymolenna are you sure you're using the latest `linkml`? I really thought @sujaypatil96 had been working on showing the `any_of` ranges. Maybe that's in a newer release than you are using?

2024-03-08 18:56 UTC, turbomam commented
This is what I ahve now, but I don't know if the poetry.lock requires the versions to be this high yet.

```
linkml                     1.7.5           Linked Open Data Modeling Language
linkml-runtime             1.7.2           Runtime environment for LinkML, ...
```

2024-03-08 19:08 UTC, turbomam commented
I just made `testdoc` in main

here's the slot definition:

```yaml
  compound:
    domain: SolutionComponent
    any_of:
      - range: CompoundEnum
      - range: ProteolyticEnzymeEnum
    description: A substance that consists of more than one atom or ion. Includes solvents and solutes. Can be combined into solutions.
    required: true
```

and here's the resulting documentation, which I agree is incorrect!

![image](https://github.com/microbiomedata/berkeley-schema-fy24/assets/25185273/fb00b6b7-4803-4b03-a16b-88944edbec93)

2024-03-08 19:33 UTC, turbomam commented
@sujaypatil96 this issue was closed. Was it intended to address cases like this?

- https://github.com/linkml/linkml/issues/1851

2024-03-11 15:59 UTC, anastasiyaprymolenna commented
Thank you for confirming Mark. Yes, the testdoc generation issue persists with the latest version of LinkML (the version I am using is the same as you have listed above). I like your suggestion to "work on some modeling that combines the two enums". If we cannot resolve the documentation generation bug, we might have to find alternate methods of representing the range of the slot altogether.

2024-03-11 19:28 UTC, sujaypatil96 commented
@anastasiyaprymolenna my apologies for the premature guidance in https://github.com/microbiomedata/nmdc-schema/issues/1666#issuecomment-1915214482, I responded without looking through the use case/schema thoroughly myself. I apologize for that.

@turbomam is right, there have been recent updates to linkml where we've added support for appropriately rendering documentation when the slot range is a union composed using `any_of` but the reason you're not seeing that applied to the generated web documentation is because those updates are not in the latest release of linkml just yet. As soon as the next release of linkml is out, we will update the poetry.lock file in the berkeley schema repository to use that release, and there will be a GitHub Action that will update the docs available at https://microbiomedata.github.io/berkeley-schema-fy24/ to appropriately render the ranges for slots using `any_of`.

2024-03-11 22:20 UTC, closed without merging